In [1]:
import numpy as np
import scipy.sparse as sparse
import scipy
from scipy.sparse import linalg


In [2]:
N = 4
d = 2*N

U = np.zeros((d,d,2,2),dtype = complex)

In [3]:
#defining matrix elements of U
r_gen = np.array([[np.exp(2*np.pi/N*1j), 0], [0, np.exp(-2*np.pi/N*1j)]])
s_gen = np.array([[0, 1], [1, 0]])

for i in range(d):
    U[i][i] = np.linalg.matrix_power(s_gen, int(np.floor(i/N)))@np.linalg.matrix_power(r_gen, i)
    print(U[i][i]
          )


[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
[[6.123234e-17+1.j 0.000000e+00+0.j]
 [0.000000e+00+0.j 6.123234e-17-1.j]]
[[-1.+1.2246468e-16j  0.+0.0000000e+00j]
 [ 0.+0.0000000e+00j -1.-1.2246468e-16j]]
[[-1.8369702e-16-1.j  0.0000000e+00+0.j]
 [ 0.0000000e+00+0.j -1.8369702e-16+1.j]]
[[0.+0.0000000e+00j 1.+2.4492936e-16j]
 [1.-2.4492936e-16j 0.+0.0000000e+00j]]
[[0.000000e+00+0.j 3.061617e-16-1.j]
 [3.061617e-16+1.j 0.000000e+00+0.j]]
[[ 0.+0.0000000e+00j -1.-3.6739404e-16j]
 [-1.+3.6739404e-16j  0.+0.0000000e+00j]]
[[ 0.0000000e+00+0.j -4.2862638e-16+1.j]
 [-4.2862638e-16-1.j  0.0000000e+00+0.j]]


In [4]:
#from group basis to representation basis (group Fourier transform)

QFTD3 = np.array([[1/np.sqrt(6), 1/np.sqrt(6), 1/np.sqrt(6), 1/np.sqrt(6), 1/np.sqrt(6), 1/np.sqrt(6)], #trivial
            [1/np.sqrt(6), 1/np.sqrt(6), 1/np.sqrt(6), -1/np.sqrt(6), -1/np.sqrt(6), -1/np.sqrt(6)], #parity
                        
            [1/np.sqrt(3), 1/np.sqrt(3)*np.exp(2*np.pi*1j/3), 1/np.sqrt(3)*np.exp(-2*np.pi*1j/3), 0, 0, 0],
            [0, 0, 0, 1/np.sqrt(3), 1/np.sqrt(3)*np.exp(-2*np.pi*1j/3), 1/np.sqrt(3)*np.exp(2*np.pi*1j/3)],
            [0, 0, 0, 1/np.sqrt(3), 1/np.sqrt(3)*np.exp(2*np.pi*1j/3), 1/np.sqrt(3)*np.exp(-2*np.pi*1j/3)],
            [1/np.sqrt(3), 1/np.sqrt(3)*np.exp(-2*np.pi*1j/3), 1/np.sqrt(3)*np.exp(2*np.pi*1j/3), 0, 0, 0]
                  ]) 

QFTD4 = np.array([
            [1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8)],
            [1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8), -1/np.sqrt(8), -1/np.sqrt(8), -1/np.sqrt(8)],
            [1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8)],
            [1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8), -1/np.sqrt(8), 1/np.sqrt(8)],
            [0.5 + 0j, 0 + 0.5j, -0.5 + 0j, 0 - 0.5j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j],
            [0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.5 + 0j, 0 - 0.5j, -0.5 + 0j, 0 + 0.5j],
            [0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.5 + 0j, 0 + 0.5j, -0.5 + 0j, 0 - 0.5j],
            [0.5 + 0j, 0 - 0.5j, -0.5 + 0j, 0 + 0.5j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j]
            ], dtype=complex)

if N == 3:
    QFT = QFTD3
elif N == 4:
    QFT = QFTD4

#nomenclature:
#reps: trivial, parity, fundamental rep.

In [5]:
#reshaping U

U_r = np.zeros((2,2,d,d),dtype = complex)

U_r[0][0] = (QFT@U[:,:,0,0]@QFT.T.conj()) #check whether QFT or QFT.T.conj() is needed
U_r[0][1] = (QFT@U[:,:,0,1]@QFT.T.conj())
U_r[1][0] = (QFT@U[:,:,1,0]@QFT.T.conj())
U_r[1][1] = (QFT@U[:,:,1,1]@QFT.T.conj())

print(np.round(np.real(U_r[0][0]),2))


[[-0.   -0.    0.    0.    0.71  0.    0.    0.  ]
 [-0.   -0.    0.    0.    0.71  0.    0.    0.  ]
 [ 0.    0.   -0.   -0.    0.    0.    0.    0.71]
 [ 0.    0.   -0.   -0.    0.    0.    0.    0.71]
 [ 0.    0.    0.71  0.71 -0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.71  0.71  0.    0.    0.    0.    0.   -0.  ]]


In [6]:
for i in range(2):
    for j in range(2):
        print(np.real(np.round(U_r[i][j],2)))#correct up to nomenclature: 00 -- up down, 01 -- down down, 10 -- up up, 11 -- down up
        print("\n")

[[-0.   -0.    0.    0.    0.71  0.    0.    0.  ]
 [-0.   -0.    0.    0.    0.71  0.    0.    0.  ]
 [ 0.    0.   -0.   -0.    0.    0.    0.    0.71]
 [ 0.    0.   -0.   -0.    0.    0.    0.    0.71]
 [ 0.    0.    0.71  0.71 -0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.71  0.71  0.    0.    0.    0.    0.   -0.  ]]


[[-0.    0.    0.   -0.    0.    0.71  0.    0.  ]
 [ 0.   -0.   -0.    0.    0.   -0.71  0.    0.  ]
 [ 0.   -0.   -0.    0.    0.    0.    0.71  0.  ]
 [-0.    0.    0.   -0.    0.    0.   -0.71  0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.71 -0.71  0.   -0.    0.    0.  ]
 [ 0.71 -0.71  0.    0.    0.    0.   -0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.  ]]


[[-0.    0.    0.   -0.    0.    0.    0.71  0.  ]
 [ 0.   -0.   -0.    0.    0.    0.   -0.71  0.  ]
 [ 0.   -0.   -0.    0.    0.    0.71  0.    0.  ]
 [-0.    0.    0.   -0.  

In [7]:
plaquette = np.zeros((d**4,d**4),dtype = complex)

plaquette = sparse.csc_matrix(plaquette)



for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                plaquette += sparse.kron(scipy.sparse.kron(scipy.sparse.csc_matrix(U_r[i][j]),sparse.csc_matrix(U_r[j][k])),sparse.kron(scipy.sparse.csc_matrix(U_r[l][k].T.conj()),sparse.csc_matrix(U_r[i][l].T.conj())))
      
    

print(np.allclose(plaquette.toarray(),plaquette.toarray().T.conj())  ) 
    
#eigenval, eigenvec = linalg.eigsh(-plaquette, k=10,which = "SA",sigma = )
eigenval, eigenvec = scipy.linalg.eigh(-plaquette.toarray())


True


In [8]:
for i in range(len(eigenval)):
    print(np.round(eigenval[i],2))

-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0
-2.0


In [9]:
# Theta operators
if N == 3:
        theta_L_r = QFT@sparse.csc_matrix(np.array([[0,0,1,0,0,0],
                                                [1,0,0,0,0,0],
                                                [0,1,0,0,0,0],
                                                [0,0,0,0,1,0],
                                                [0,0,0,0,0,1],
                                                [0,0,0,1,0,0]]))@QFT.T.conj()

        theta_L_s = QFT@sparse.csc_matrix(np.array([[0,0,0,1,0,0],
                                                [0,0,0,0,1,0],
                                                [0,0,0,0,0,1],
                                                [1,0,0,0,0,0],
                                                [0,1,0,0,0,0],
                                                [0,0,1,0,0,0]]))@QFT.T.conj()

        theta_R_r = QFT@sparse.csc_matrix(np.array([[0,1,0,0,0,0],
                                                [0,0,1,0,0,0],
                                                [1,0,0,0,0,0],
                                                [0,0,0,0,1,0],
                                                [0,0,0,0,0,1],
                                                [0,0,0,1,0,0]]))@QFT.T.conj()

        theta_R_s = QFT@sparse.csc_matrix(np.array([[0,0,0,1,0,0],
                                                [0,0,0,0,0,1],
                                                [0,0,0,0,1,0],
                                                [1,0,0,0,0,0],
                                                [0,0,1,0,0,0],
                                                [0,1,0,0,0,0]]))@QFT.T.conj()
elif N == 4:
        theta_L_r = QFT@sparse.csc_matrix(np.array([[0,0,0,1,0,0,0,0],
                                                    [1,0,0,0,0,0,0,0],
                                                    [0,1,0,0,0,0,0,0],
                                                    [0,0,1,0,0,0,0,0],
                                                    [0,0,0,0,0,1,0,0],
                                                    [0,0,0,0,0,0,1,0],
                                                    [0,0,0,0,0,0,0,1],
                                                    [0,0,0,0,1,0,0,0]]))@QFT.T.conj()

        theta_L_s = QFT@sparse.csc_matrix(np.array([[0,0,0,0,1,0,0,0],
                                                    [0,0,0,0,0,1,0,0],
                                                    [0,0,0,0,0,0,1,0],
                                                    [0,0,0,0,0,0,0,1],
                                                    [1,0,0,0,0,0,0,0],
                                                    [0,1,0,0,0,0,0,0],
                                                    [0,0,1,0,0,0,0,0],
                                                    [0,0,0,1,0,0,0,0]]))@QFT.T.conj()

        theta_R_r = QFT@sparse.csc_matrix(np.array([[0,1,0,0,0,0,0,0],
                                                    [0,0,1,0,0,0,0,0],
                                                    [0,0,0,1,0,0,0,0],
                                                    [1,0,0,0,0,0,0,0],
                                                    [0,0,0,0,0,1,0,0],
                                                    [0,0,0,0,0,0,1,0],
                                                    [0,0,0,0,0,0,0,1],
                                                    [0,0,0,0,1,0,0,0]]))@QFT.T.conj()

        theta_R_s = QFT@sparse.csc_matrix(np.array([[0,0,0,0,1,0,0,0],
                                                    [0,0,0,0,0,0,0,1],
                                                    [0,0,0,0,0,0,1,0],
                                                    [0,0,0,0,0,1,0,0],
                                                    [1,0,0,0,0,0,0,0],
                                                    [0,0,0,1,0,0,0,0],
                                                    [0,0,1,0,0,0,0,0],
                                                    [0,1,0,0,0,0,0,0]]))@QFT.T.conj()




In [10]:
print(np.round(theta_L_r,2))
print(np.round(theta_R_r,2))

[[ 1.+0.j  0.+0.j -0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j -0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -0.+0.j -1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+1.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+1.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-1.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-1.j]]
[[ 1.+0.j  0.+0.j -0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j -0.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j -0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -0.+0.j -1.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-1.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+1.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j  0.-1.j  0.

In [11]:
Gauss_r_dl = sparse.kron(sparse.kron(sparse.kron(theta_L_r,np.eye(d)),np.eye(d)),theta_L_r)
Gauss_s_dl = sparse.kron(sparse.kron(sparse.kron(theta_L_s,np.eye(d)),np.eye(d)),theta_L_s)

Gauss_r_dr = sparse.kron(sparse.kron(sparse.kron(theta_R_r,theta_L_r),np.eye(d)),np.eye(d))
Gauss_s_dr = sparse.kron(sparse.kron(sparse.kron(theta_R_s,theta_L_s),np.eye(d)),np.eye(d))

Gauss_r_ur = sparse.kron(sparse.kron(sparse.kron(np.eye(d),theta_R_r),theta_R_r),np.eye(d))
Gauss_s_ur = sparse.kron(sparse.kron(sparse.kron(np.eye(d),theta_R_s),theta_R_s),np.eye(d))

Gauss_r_ul = sparse.kron(sparse.kron(sparse.kron(np.eye(d),np.eye(d)),theta_L_r),theta_R_r)
Gauss_s_ul = sparse.kron(sparse.kron(sparse.kron(np.eye(d),np.eye(d)),theta_L_s),theta_R_s)

In [12]:
A = Gauss_r_ul@plaquette
B = plaquette@Gauss_r_ul
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_s_ul@plaquette
B = plaquette@Gauss_s_ul
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_r_ur@plaquette
B = plaquette@Gauss_r_ur
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_s_ur@plaquette
B = plaquette@Gauss_s_ur
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_r_dl@plaquette
B = plaquette@Gauss_r_dl
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_s_dl@plaquette
B = plaquette@Gauss_s_dl
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_r_dr@plaquette
B = plaquette@Gauss_r_dr
print(np.allclose(A.toarray(),B.toarray()))
A = Gauss_s_dr@plaquette
B = plaquette@Gauss_s_dr
print(np.allclose(A.toarray(),B.toarray()))


True
True
True
True
True
True
True
True


In [13]:
pen = 10
plaquette = np.zeros((d**4,d**4),dtype = complex)

plaquette = sparse.csc_matrix(plaquette)



for i in range(2):
    for j in range(2):
        for k in range(2):
            for l in range(2):
                plaquette -= sparse.kron(scipy.sparse.kron(scipy.sparse.csc_matrix(U_r[i][j]),sparse.csc_matrix(U_r[j][k])),sparse.kron(scipy.sparse.csc_matrix(U_r[l][k].T.conj()),sparse.csc_matrix(U_r[i][l].T.conj())))

                
plaquette += pen*(Gauss_r_ul-sparse.identity(d**4))@(Gauss_r_ul-sparse.identity(d**4))
plaquette += pen*(Gauss_s_ul-sparse.identity(d**4))@(Gauss_s_ul-sparse.identity(d**4))

plaquette += pen*(Gauss_r_ur-sparse.identity(d**4))@(Gauss_r_ur-sparse.identity(d**4))
plaquette += pen*(Gauss_s_ur-sparse.identity(d**4))@(Gauss_s_ur-sparse.identity(d**4))

plaquette += pen*(Gauss_r_dl-sparse.identity(d**4))@(Gauss_r_dl-sparse.identity(d**4))
plaquette += pen*(Gauss_s_dl-sparse.identity(d**4))@(Gauss_s_dl-sparse.identity(d**4))

plaquette += pen*(Gauss_r_dr-sparse.identity(d**4))@(Gauss_r_dr-sparse.identity(d**4))
plaquette += pen*(Gauss_s_dr-sparse.identity(d**4))@(Gauss_s_dr-sparse.identity(d**4))


print(np.allclose(plaquette.toarray(),plaquette.toarray().T.conj())  ) 
    
#eigenval, eigenvec = linalg.eigsh(-plaquette, k=10,which = "SA",sigma = )
eigenval, eigenvec = scipy.linalg.eig(plaquette.toarray())
idx = np.argsort(eigenval.real)

# Sort eigenvalues and eigenvectors accordingly
eigvals_sorted = eigenval[idx]
eigvecs_sorted = eigenvec[:,idx]
print(eigvals_sorted)

False
[-2.00000000e+00-4.14551476e-16j  1.78369544e-14+5.37921800e-17j
  1.62840483e-13-5.40210604e-15j ...  3.20000000e+02+2.25134581e-14j
  3.20000000e+02-5.15278399e-16j  3.22000000e+02-1.86389126e-14j]


In [14]:
for i in range(len(eigvecs_sorted[:,0])):
    if np.abs(eigvecs_sorted[:,0][i])>1e-2:
        print(i,eigvecs_sorted[:,0][i],i%d,int((i-i%d)/d)%d,int((i-i%d)/d**2)%d,int((i-i%d)/d**3)%d)

0 (0.3535533905932544-9.147955830346444e-20j) 0 0 0 0
585 (0.35355339059327945+0j) 1 1 1 1
1170 (0.35355339059327945-1.8634724839594607e-19j) 2 2 2 2
1755 (0.3535533905932794-2.236166980751353e-19j) 3 3 3 3
2350 (0.17677669529663712-1.840094374615242e-17j) 6 5 4 4
2367 (0.17677669529663723-2.0328790734103208e-20j) 7 7 4 4
2406 (0.17677669529663737-1.8443295393515136e-17j) 6 4 5 4
2423 (0.17677669529663737+1.6940658945086007e-20j) 7 6 5 4
2990 (0.1767766952966371-1.5246593050577406e-20j) 6 5 6 5
3007 (0.17677669529663723+1.841280220741398e-17j) 7 7 6 5
3046 (0.17677669529663723+1.1858461261560205e-20j) 6 4 7 5
3063 (0.1767766952966371+1.8467012316038256e-17j) 7 6 7 5
3372 (0.17677669529663703-1.8417884405097507e-17j) 4 5 4 6
3389 (0.17677669529663714-1.6940658945086007e-21j) 5 7 4 6
3428 (0.17677669529663717-1.8480564843194325e-17j) 4 4 5 6
3445 (0.17677669529663712-1.3552527156068805e-20j) 5 6 5 6
4012 (0.17677669529663728+3.3881317890172014e-21j) 4 5 6 7
4029 (0.1767766952966372+1.844

In [15]:
#rishon operators
if N == 3:
        rish_dim = 4
        n_rish = 3
        rishons = np.zeros((3,2,rish_dim,rish_dim),dtype = complex)
        rishons[0][0] =np.array([
                                [0,0,0,0],
                                [0,0,1,0],
                                [0,0,0,0],
                                [1,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[0][1] =np.array([
                                [0,0,0,0],
                                [0,0,0,-1],
                                [1,0,0,0],
                                [0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[1][0] =np.array([
                                [0,0,1,0],
                                [0,0,0,0],
                                [0,0,0,0],
                                [0,-1,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[1][1] =np.array([
                                [0,0,0,1],
                                [0,0,0,0],
                                [0,1,0,0],
                                [0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[2][0] =np.array([
                                [0,0,0,0],
                                [0,0,0,0],
                                [0,0,0,1],
                                [0,0,0,0]
                                        ])
        rishons[2][1] =np.array([
                                [0,0,0,0],
                                [0,0,0,0],
                                [0,0,0,0],
                                [0,0,1,0]
                                        ])
        
elif N == 4:
        rish_dim = 6
        n_rish = 4
        rishons = np.zeros((4,2,rish_dim,rish_dim),dtype = complex)
        rishons[0][0] =np.array([
                                [0,0,0,0,1,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [1,0,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[0][1] =np.array([
                                [0,0,0,0,0,1],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [1,0,0,0,0,0],
                                [0,0,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[1][0] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,1,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,-1,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[1][1] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,-1],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,1,0,0,0,0],
                                [0,0,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[2][0] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,1],
                                [0,0,0,0,0,0],
                                [0,0,1,0,0,0],
                                [0,0,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[2][1] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,1,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,1,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[3][0] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,-1],
                                [0,0,0,1,0,0],
                                [0,0,0,0,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        rishons[3][1] =np.array([
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,0,0],
                                [0,0,0,0,1,0],
                                [0,0,0,0,0,0],
                                [0,0,0,-1,0,0]
                                        ])/np.sqrt(np.sqrt(2))
        


In [16]:
i_index = 0
j_index = 1

if N == 3:
        penalty_A = np.diag(np.array([1,-1,2,2]))
        penalty_B = np.diag(np.array([1,-1,1/2,1/2]))
elif N == 4:
        penalty_A = np.diag(np.array([1,-1,2,7,4,4]))
        penalty_B = np.diag(np.array([1,-1,1/2,1/7,1/4,1/4]))
        

penalty_composite = 100000*(np.kron(penalty_A,penalty_B)-np.eye(rish_dim**2))**2


In [17]:
"""M_01 = np.kron(rishons[0][i_index],rishons[1][(j_index+1)%2].T.conj())
M_10 = np.kron(rishons[1][i_index],rishons[0][(j_index+1)%2].T.conj())
M_22 = np.kron(rishons[2][i_index],rishons[2][(j_index+1)%2].T.conj())

M = M_01 + M_10 + M_22 + penalty_composite

M_sum = M_01 + M_10 + M_22

print(np.allclose(M_sum@penalty_composite,penalty_composite@M_sum))


M_reduced = np.zeros((6,6),dtype = complex)

# Indices to remove
rows_to_remove = [1,2,3,4,6,7,8,9,12,13]
cols_to_remove = [1,2,3,4,6,7,8,9,12,13]

# Remove rows
M_reduced = np.delete(M, rows_to_remove, axis=0)
penalty_reduced = np.delete(penalty_composite, rows_to_remove, axis=0)

# Remove columns
M_reduced = np.delete(M_reduced, cols_to_remove, axis=1)
penalty_reduced = np.delete(penalty_reduced, cols_to_remove, axis=1)


print(np.real(penalty_reduced))
print(np.real(np.round(M_reduced,2)))
print(np.real(np.round(U_r[i_index][j_index],2)))

print(np.allclose(M_reduced,U_r[i_index][j_index]))"""

'M_01 = np.kron(rishons[0][i_index],rishons[1][(j_index+1)%2].T.conj())\nM_10 = np.kron(rishons[1][i_index],rishons[0][(j_index+1)%2].T.conj())\nM_22 = np.kron(rishons[2][i_index],rishons[2][(j_index+1)%2].T.conj())\n\nM = M_01 + M_10 + M_22 + penalty_composite\n\nM_sum = M_01 + M_10 + M_22\n\nprint(np.allclose(M_sum@penalty_composite,penalty_composite@M_sum))\n\n\nM_reduced = np.zeros((6,6),dtype = complex)\n\n# Indices to remove\nrows_to_remove = [1,2,3,4,6,7,8,9,12,13]\ncols_to_remove = [1,2,3,4,6,7,8,9,12,13]\n\n# Remove rows\nM_reduced = np.delete(M, rows_to_remove, axis=0)\npenalty_reduced = np.delete(penalty_composite, rows_to_remove, axis=0)\n\n# Remove columns\nM_reduced = np.delete(M_reduced, cols_to_remove, axis=1)\npenalty_reduced = np.delete(penalty_reduced, cols_to_remove, axis=1)\n\n\nprint(np.real(penalty_reduced))\nprint(np.real(np.round(M_reduced,2)))\nprint(np.real(np.round(U_r[i_index][j_index],2)))\n\nprint(np.allclose(M_reduced,U_r[i_index][j_index]))'

In [18]:
def corner_operators_rishons(i,j,pos):
    
    corner_op = np.zeros((rish_dim**2,rish_dim**2),dtype = complex)
    
    if pos%4 == 0:

        for k in range(2):
            
            corner_op += np.kron(rishons[i][k].T.conj(),rishons[j][k])
            
    elif pos%4 == 1:

        for k in range(2):
        
            corner_op += np.kron(rishons[i][(k+1)%2],rishons[j][k].T.conj())        
            #corner_op += np.kron(rishons[i][k],rishons[j][k].T.conj())        

    elif pos%4 == 2:

        for k in range(2):
        
            corner_op += np.kron(rishons[i][(k+1)%2].T.conj(),rishons[j][k])
            #corner_op += np.kron(rishons[i][k].T.conj(),rishons[j][k])
    
    elif pos%4 == 3:

        for k in range(2):
        
            corner_op += np.kron(rishons[i][k],rishons[j][k].T.conj())
            
    return corner_op

In [19]:
CC = np.zeros((4,N,N,rish_dim**2,rish_dim**2),dtype = complex) # I write N because the number of rishon is, by chance, = N


for n in range(4):
    for i in range(N):
        for j in range(N):
            CC[n][i][j] = corner_operators_rishons(i,j,n)

In [20]:
#Define transformation matrices here (4x4)

w = np.exp(2*1j*np.pi/N)
if N == 3:
        Theta_L_s = np.array([[1,0,0,0],
                            [0,-1,0,0],
                            [0,0,0,1],
                            [0,0,1,0]])

        Theta_R_s = np.array([[1,0,0,0],
                            [0,-1,0,0],
                            [0,0,0,1],
                            [0,0,1,0]])

        Theta_L_r = np.array([[1,0,0,0],
                            [0,1,0,0],
                            [0,0,w,0],
                            [0,0,0,w**2]])

        Theta_R_r = np.array([[1,0,0,0],
                            [0,1,0,0],
                            [0,0,w**2,0],
                            [0,0,0,w]])
elif N == 4:
        Theta_L_s = np.array([[1,0,0,0,0,0],
                              [0,-1,0,0,0,0],
                              [0,0,1,0,0,0],
                              [0,0,0,-1,0,0],
                              [0,0,0,0,0,1],
                              [0,0,0,0,1,0]])

        Theta_R_s = Theta_L_s

        Theta_L_r = np.array([[1,0,0,0,0,0],
                              [0,1,0,0,0,0],
                              [0,0,-1,0,0,0],
                              [0,0,0,-1,0,0],
                              [0,0,0,0,w,0],
                              [0,0,0,0,0,w**(-1)]])

        Theta_R_r = np.array([[1,0,0,0,0,0],
                              [0,1,0,0,0,0],
                              [0,0,-1,0,0,0],
                              [0,0,0,-1,0,0],
                              [0,0,0,0,w**(-1),0],
                              [0,0,0,0,0,w]])

#Construct Gauss's laws operators here for upper left edge (16x16 matrices)

G_s_ul_rish = np.kron(Theta_R_s,Theta_L_s)
G_r_ul_rish = np.kron(Theta_R_r,Theta_L_r)

gauss_ul_rish = ((G_s_ul_rish-np.eye(rish_dim**2))@(G_s_ul_rish-np.eye(rish_dim**2)) + (G_r_ul_rish-np.eye(rish_dim**2))@(G_r_ul_rish-np.eye(rish_dim**2)))


#Construct Gauss's laws operators here for lower left edge (16x16 matrices)

G_s_dl_rish = np.kron(Theta_L_s,Theta_L_s)
G_r_dl_rish = np.kron(Theta_L_r,Theta_L_r)

gauss_dl_rish = ((G_s_dl_rish-np.eye(rish_dim**2))@(G_s_dl_rish-np.eye(rish_dim**2)) + (G_r_dl_rish-np.eye(rish_dim**2))@(G_r_dl_rish-np.eye(rish_dim**2)))

#Construct Gauss's laws operators here for upper right edge (16x16 matrices)

G_s_ur_rish = np.kron(Theta_R_s,Theta_R_s)
G_r_ur_rish = np.kron(Theta_R_r,Theta_R_r)

gauss_ur_rish = ((G_s_ur_rish-np.eye(rish_dim**2))@(G_s_ur_rish-np.eye(rish_dim**2)) + (G_r_ur_rish-np.eye(rish_dim**2))@(G_r_ur_rish-np.eye(rish_dim**2)))

#Construct Gauss's laws operators here for lower right edge (16x16 matrices)

G_s_dr_rish = np.kron(Theta_R_s,Theta_L_s)
G_r_dr_rish = np.kron(Theta_R_r,Theta_L_r)

gauss_dr_rish = ((G_s_dr_rish-np.eye(rish_dim**2))@(G_s_dr_rish-np.eye(rish_dim**2)) + (G_r_dr_rish-np.eye(rish_dim**2))@(G_r_dr_rish-np.eye(rish_dim**2)))


In [21]:
if N == 3: 
    liste = [1,0,2]
elif N == 4:
    liste = [0,1,2,3]
    
pen = 10
penalty_A = sparse.csc_matrix(penalty_A)
penalty_B = sparse.csc_matrix(penalty_B)

pr = 0
for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]

                                
                pr -= sparse.kron(sparse.kron(CC[0][i_c][j],CC[1][i][l]),sparse.kron(CC[2][j_c][k],CC[3][l_c][k_c]))

"""liste = [1,0,2]

penalty_A = sparse.csc_matrix(penalty_A)
penalty_B = sparse.csc_matrix(penalty_B)

pr = 0
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]

                                
                pr -= sparse.kron(sparse.kron(CC[0][i_c][j],CC[1][i][l]),sparse.kron(CC[2][j_c][k],CC[3][l_c][k_c]))"""
                
pr += 10*(sparse.kron(sparse.kron(sparse.kron(penalty_A,sparse.eye(rish_dim)),penalty_B),sparse.eye(rish_dim**5))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim),penalty_A),sparse.eye(rish_dim**2)),penalty_B),sparse.eye(rish_dim**3))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim**3),penalty_A),sparse.eye(rish_dim**2)),penalty_B),sparse.eye(rish_dim))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim**5),penalty_A),sparse.eye(rish_dim)),penalty_B)-sparse.eye(rish_dim**8))**2



In [22]:
for i in range(N):
    for j in range(N):
        print(np.allclose(G_s_dl_rish@CC[0][i][j],CC[0][i][j]@G_s_dl_rish))
        print(np.allclose(G_r_dl_rish@CC[0][i][j],CC[0][i][j]@G_r_dl_rish))
        
for i in range(N):
    for j in range(N):
        print(np.allclose(G_s_ul_rish@CC[1][i][j],CC[1][i][j]@G_s_ul_rish))
        print(np.allclose(G_r_ul_rish@CC[1][i][j],CC[1][i][j]@G_r_ul_rish))

for i in range(N):
    for j in range(N):
        print(np.allclose(G_s_dr_rish@CC[2][i][j],CC[2][i][j]@G_s_dr_rish))
        print(np.allclose(G_r_dr_rish@CC[2][i][j],CC[2][i][j]@G_r_dr_rish))
        
for i in range(N):
    for j in range(N):
        print(np.allclose(G_s_ur_rish@CC[3][i][j],CC[3][i][j]@G_s_ur_rish))
        print(np.allclose(G_r_ur_rish@CC[3][i][j],CC[3][i][j]@G_r_ur_rish))
        

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [23]:
if N == 3: 
    liste = [1,0,2]
elif N == 4:
    liste = [0,1,2,3]
    
pen = 10
penalty_A = sparse.csc_matrix(penalty_A)
penalty_B = sparse.csc_matrix(penalty_B)

pr = 0
for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]

                                
                pr -= sparse.kron(sparse.kron(CC[0][i_c][j],CC[1][i][l]),sparse.kron(CC[2][j_c][k],CC[3][l_c][k_c]))
                
                
pr += 10*(sparse.kron(sparse.kron(sparse.kron(penalty_A,sparse.eye(rish_dim)),penalty_B),sparse.eye(rish_dim**5))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim),penalty_A),sparse.eye(rish_dim**2)),penalty_B),sparse.eye(rish_dim**3))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim**3),penalty_A),sparse.eye(rish_dim**2)),penalty_B),sparse.eye(rish_dim))-sparse.eye(rish_dim**8))**2

pr += 10*(sparse.kron(sparse.kron(sparse.kron(sparse.eye(rish_dim**5),penalty_A),sparse.eye(rish_dim)),penalty_B)-sparse.eye(rish_dim**8))**2

pr += pen*sparse.kron(gauss_dl_rish,sparse.eye((rish_dim**2)**3))
pr += pen*sparse.kron(sparse.kron(sparse.eye((rish_dim**2)),gauss_ul_rish),sparse.eye((rish_dim**2)**2))
pr += pen*sparse.kron(sparse.kron(sparse.eye((rish_dim**2)**2),gauss_dr_rish),sparse.eye((rish_dim**2)))
pr += pen*sparse.kron(sparse.eye((rish_dim**2)**3),gauss_ur_rish)


In [25]:
scipy.__version__

'1.15.3'

In [ ]:
# scipy.sparse.linalg.LinearOperator.H

# pr.H

# print(pr.H-pr)

AttributeError: 'csr_matrix' object has no attribute 'H'

In [26]:
from scipy.sparse import linalg

eigenval, eigenvec = linalg.eigs(pr, k=2,which = "SR")
print(np.real(eigenval))

[-2.  2.]


In [27]:
for i in range(len(eigenvec[:,0])):
    
    if np.abs(eigenvec[:,0][i])>1e-10:
        #print(i,eigenvec[:,0][i])
         
        print(i,eigenvec[:,0][i],i%rish_dim,(int((i-i%rish_dim)/rish_dim))%rish_dim,(int((i-i%rish_dim)/rish_dim**2))%rish_dim,(int((i-i%rish_dim)/rish_dim**3))%rish_dim,(int((i-i%rish_dim)/rish_dim**rish_dim))%rish_dim,(int((i-i%rish_dim)/rish_dim**5))%rish_dim,(int((i-i%rish_dim)/rish_dim**6))%rish_dim,(int((i-i%rish_dim)/rish_dim**7))%rish_dim)

0 (-0.019793850190090258+0.3529988718036479j) 0 0 0 0 0 0 0 0
335923 (-0.019793850190090258+0.3529988718036479j) 1 1 1 1 1 1 1 1
671846 (-0.019793850190090258+0.3529988718036479j) 2 2 2 2 2 2 2 2
1007769 (-0.019793850190090258+0.3529988718036479j) 3 3 3 3 3 3 3 3
1390349 (-0.00989692509503998+0.17649943590182765j) 5 4 4 4 5 4 5 4
1390354 (-0.009896925095039977+0.17649943590182757j) 4 5 4 4 5 4 5 4
1390601 (-0.009896925095039973+0.1764994359018274j) 5 4 5 5 5 4 5 4
1390606 (-0.009896925095039963+0.17649943590182732j) 4 5 5 5 5 4 5 4
1399421 (-0.009896925095039972+0.1764994359018276j) 5 4 4 4 5 5 5 4
1399426 (-0.00989692509503997+0.17649943590182748j) 4 5 4 4 5 5 5 4
1399673 (-0.009896925095039965+0.1764994359018277j) 5 4 5 5 5 5 5 4
1399678 (-0.009896925095039977+0.1764994359018275j) 4 5 5 5 5 5 5 4
1623629 (-0.009896925095039975+0.1764994359018276j) 5 4 4 4 4 4 4 5
1623634 (-0.009896925095039968+0.17649943590182765j) 4 5 4 4 4 4 4 5
1623881 (-0.009896925095039947+0.17649943590182765j) 

In [28]:
def corner_operators(i,j,pos):
    
    corner_op = np.zeros((rish_dim**3,rish_dim**3),dtype = complex)
    
    
    if pos%4 == 0:

        for k in range(2): #Left Left
            corner_op += np.kron(np.eye(rish_dim),np.kron(rishons[i][k].T.conj(),rishons[j][k]))
            
    elif pos%4 == 1:

        for k in range(2):  #Right Left
        
            corner_op += np.kron(np.eye(rish_dim),np.kron(rishons[i][(k+1)%2],rishons[j][k].T.conj()))        
            #corner_op += np.kron(np.eye(rish_dim),np.kron(rishons[i][k],rishons[j][k].T.conj()))        

    
    elif pos%4 == 2:

        for k in range(2):  #Right Left
        
            corner_op += np.kron(np.kron(rishons[i][(k+1)%2].T.conj(),rishons[j][k]),np.eye(rish_dim))
            #corner_op += np.kron(np.kron(rishons[i][k].T.conj(),rishons[j][k]),np.eye(rish_dim))

            
    
    elif pos%4 == 3:

        for k in range(2):  #Right Right
            corner_op += np.kron(np.kron(rishons[i][(k+1)%2],rishons[j][(k+1)%2].T.conj()),np.eye(rish_dim))
            
            
    return corner_op

In [29]:
def corner_operators_edge(i,j,pos,charge):
    
    if pos%4 == 0:
        
        corner_op = np.zeros((rish_dim**2,rish_dim**2),dtype = complex)

        for k in range(2):
            corner_op += np.kron(rishons[i][k].T.conj(),rishons[j][k])
            
    elif pos%4 == 1:
        if charge%2 == 1:
            corner_op = np.zeros((2*rish_dim**2,2*rish_dim**2),dtype = complex)


            for k in range(2):

                corner_op += np.kron(np.kron(rishons[i][(k+1)%2],rishons[j][k].T.conj()),np.eye(2))
                #corner_op += np.kron(np.kron(rishons[i][k],rishons[j][k].T.conj()),np.eye(2))

        else:
            corner_op = np.zeros((rish_dim**2,rish_dim**2),dtype = complex)


            for k in range(2):

                corner_op += np.kron(rishons[i][(k+1)%2],rishons[j][k].T.conj())           
                #corner_op += np.kron(rishons[i][k],rishons[j][k].T.conj())           


    elif pos%4 == 2:
        corner_op = np.zeros((rish_dim**2,rish_dim**2),dtype = complex)

        for k in range(2):
            corner_op += np.kron(rishons[i][(k+1)%2].T.conj(),rishons[j][k])
            #corner_op += np.kron(rishons[i][k].T.conj(),rishons[j][k])

            
    
    elif pos%4 == 3:
        if charge%2 == 1:

            corner_op = np.zeros((2*rish_dim**2,2*rish_dim**2),dtype = complex)

            for k in range(2):
                corner_op += np.kron(np.kron(rishons[i][(k+1)%2],rishons[j][(k+1)%2].T.conj()),np.eye(2))
                
        else:
            corner_op = np.zeros((rish_dim**2,rish_dim**2),dtype = complex)

            for k in range(2):
                corner_op += np.kron(rishons[i][(k+1)%2],rishons[j][(k+1)%2].T.conj())
            
    return corner_op

In [30]:
CC = np.zeros((4,N,N,rish_dim**3,rish_dim**3),dtype = complex)

for n in range(4):
    for i in range(N):
        for j in range(N):
            CC[n][i][j] = corner_operators(i,j,n)

In [31]:
CC_d_edge = np.zeros((2,N,N,rish_dim**2,rish_dim**2),dtype = complex)

for n in [0,2]:
    for i in range(N):
        for j in range(N):
            CC_d_edge[int(n/2)][i][j] = corner_operators_edge(i,j,n,0)
            
            
CC_u_edge = np.zeros((2,N,N,2*rish_dim**2,2*rish_dim**2),dtype = complex)

for n in [1,3]:
    for i in range(N):
        for j in range(N):
            CC_u_edge[int(n/2)][i][j] = corner_operators_edge(i,j,n,1)

In [32]:
CC_u_edge_0 = np.zeros((2,N,N,rish_dim**2,rish_dim**2),dtype = complex)

for n in [1,3]:
    for i in range(N):
        for j in range(N):
            CC_u_edge_0[int(n/2)][i][j] = corner_operators_edge(i,j,n,0)

In [33]:
#Define transformation matrices here (4x4)

"""w = np.exp(2*1j*np.pi/3)

Theta_L_s = np.array([[1,0,0,0],
                     [0,-1,0,0],
                     [0,0,0,1],
                     [0,0,1,0]])

Theta_R_s = np.array([[1,0,0,0],
                     [0,-1,0,0],
                     [0,0,0,1],
                     [0,0,1,0]])

Theta_L_r = np.array([[1,0,0,0],
                     [0,1,0,0],
                     [0,0,w,0],
                     [0,0,0,w**2]])

Theta_R_r = np.array([[1,0,0,0],
                     [0,1,0,0],
                     [0,0,w**2,0],
                     [0,0,0,w]])"""


Theta_charge_s = np.array([
                     [0,1],
                     [1,0]])


Theta_charge_r = np.array([
                     [w**(-1),0],
                     [0,w]])

#Construct Gauss's laws operators here (rish_dim**3xrish_dim**3 matrices)

G_u_s = np.kron(np.kron(Theta_R_s,Theta_R_s),Theta_L_s)
G_u_r = np.kron(np.kron(Theta_R_r,Theta_R_r),Theta_L_r)

G_d_s = np.kron(np.kron(Theta_R_s,Theta_L_s),Theta_L_s)
G_d_r = np.kron(np.kron(Theta_R_r,Theta_L_r),Theta_L_r)

gauss_u = ((G_u_s-np.eye(rish_dim**3))@(G_u_s-np.eye(rish_dim**3)) + (G_u_r-np.eye(rish_dim**3))@(G_u_r-np.eye(rish_dim**3)))

gauss_d = ((G_d_s-np.eye(rish_dim**3))@(G_d_s-np.eye(rish_dim**3)) + (G_d_r-np.eye(rish_dim**3))@(G_d_r-np.eye(rish_dim**3)))


#Construct Gauss's laws operators here for upper left edge (2*6**2x2*6**2 matrices)

G_s_ul = np.kron(np.kron(Theta_R_s,Theta_L_s),Theta_charge_s)
G_r_ul = np.kron(np.kron(Theta_R_r,Theta_L_r),Theta_charge_r)

#gauss_ul = ((G_s_ul-np.eye(2*6**2))@(G_s_ul-np.eye(2*6**2)) + (G_r_ul-np.eye(2*6**2))@(G_r_ul-np.eye(2*6**2)))
gauss_ul = ((G_s_ul-np.eye(2*rish_dim**2))@(G_s_ul-np.eye(2*rish_dim**2)) + (G_r_ul-np.eye(2*rish_dim**2))@(G_r_ul-np.eye(2*rish_dim**2)))

#Construct Gauss's laws operators here for lower left edge (rish_dim**2xrish_dim**2 matrices)

G_s_dl = np.kron(Theta_L_s,Theta_L_s)
G_r_dl = np.kron(Theta_L_r,Theta_L_r)

gauss_dl = ((G_s_dl-np.eye(rish_dim**2))@(G_s_dl-np.eye(rish_dim**2)) + (G_r_dl-np.eye(rish_dim**2))@(G_r_dl-np.eye(rish_dim**2)))

#Construct Gauss's laws operators here for upper right edge (2*6**2x2*6**2 matrices)

G_s_ur = np.kron(np.kron(Theta_R_s,Theta_R_s),Theta_charge_s)
G_r_ur = np.kron(np.kron(Theta_R_r,Theta_R_r),Theta_charge_r)

#gauss_ur = ((G_s_ur-np.eye(2*6**2))@(G_s_ur-np.eye(2*6**2)) + (G_r_ur-np.eye(2*6**2))@(G_r_ur-np.eye(2*6**2)))
gauss_ur = ((G_s_ur-np.eye(2*rish_dim**2))@(G_s_ur-np.eye(2*rish_dim**2)) + (G_r_ur-np.eye(2*rish_dim**2))@(G_r_ur-np.eye(2*rish_dim**2)))

#Construct Gauss's laws operators here for lower right edge (rish_dim**2xrish_dim**2 matrices)

G_s_dr = np.kron(Theta_R_s,Theta_L_s)
G_r_dr = np.kron(Theta_R_r,Theta_L_r)

gauss_dr = ((G_s_dr-np.eye(rish_dim**2))@(G_s_dr-np.eye(rish_dim**2)) + (G_r_dr-np.eye(rish_dim**2))@(G_r_dr-np.eye(rish_dim**2)))


#Construct Gauss's laws operators here for upper left edge 0 (rish_dim**2xrish_dim**2 matrices)

G_s_ul_0 = np.kron(Theta_R_s,Theta_L_s)
G_r_ul_0 = np.kron(Theta_R_r,Theta_L_r)

gauss_ul_0 = ((G_s_ul_0-np.eye(rish_dim**2))@(G_s_ul_0-np.eye(rish_dim**2)) + (G_r_ul_0-np.eye(rish_dim**2))@(G_r_ul_0-np.eye(rish_dim**2)))

#Construct Gauss's laws operators here for upper right edge 0 (rish_dim**2xrish_dim**2 matrices)

G_s_ur_0 = np.kron(Theta_R_s,Theta_R_s)
G_r_ur_0 = np.kron(Theta_R_r,Theta_R_r)

gauss_ur_0 = ((G_s_ur_0-np.eye(rish_dim**2))@(G_s_ur_0-np.eye(rish_dim**2)) + (G_r_ur_0-np.eye(rish_dim**2))@(G_r_ur_0-np.eye(rish_dim**2)))


In [34]:
if N == 3:
        def index_to_string_u(index):
            list_of_states_R = ["0","p","r","g"]
            list_of_states_L = ["0","p","r","g"]

            right = list_of_states_L[int(index%4)]
            center = list_of_states_R[int(((index-index%4)/4)%4)]
            left = list_of_states_R[int(((index-index%4)/16)%4)]
            
            return left+center+right
        
        def index_to_string_d(index):
            list_of_states_R = ["0","p","r","g"]
            list_of_states_L = ["0","p","r","g"]

            right = list_of_states_L[int(index%4)]
            center = list_of_states_L[int(((index-index%4)/4)%4)]
            left = list_of_states_R[int(((index-index%4)/16)%4)]
            
            return left+center+right
elif N == 4:
        def index_to_string_u(index):
            list_of_states_R = ["0","p","p1","p2","r","g"]
            list_of_states_L = ["0","p","p1","p2","r","g"]

            right = list_of_states_L[int(index%rish_dim)]
            center = list_of_states_R[int(((index-index%rish_dim)/rish_dim)%rish_dim)]
            left = list_of_states_R[int(((index-index%rish_dim)/rish_dim**2)%rish_dim)]
            
            return left+center+right
        
        def index_to_string_d(index):
            list_of_states_R = ["0","p","p1","p2","r","g"]
            list_of_states_L = ["0","p","p1","p2","r","g"]

            right = list_of_states_L[int(index%rish_dim)]
            center = list_of_states_L[int(((index-index%rish_dim)/rish_dim)%rish_dim)]
            left = list_of_states_R[int(((index-index%rish_dim)/rish_dim**2)%rish_dim)]
            
            return left+center+right

def index_to_string_edge(index,pos,charge):
    if N == 3:
            list_of_states_R = ["0","p","r","g"]
            list_of_states_L = ["0","p","r","g"]
    elif N == 4:
            list_of_states_R = ["0","p","p1","p2","r","g"]
            list_of_states_L = ["0","p","p1","p2","r","g"]
    
    list_of_states_ch = ["r","g"]

    if pos%4 == 0:
        
        right = list_of_states_L[int(index%rish_dim)]
        center = list_of_states_L[int(((index-index%rish_dim)/rish_dim)%rish_dim)]

        return center+right


    elif pos%4 == 1:
        if charge%2 == 1:
        
            charge = list_of_states_ch[int(index%2)]
            right = list_of_states_L[int(((index-index%2)/2)%rish_dim)]
            center = list_of_states_R[int(((index-index%2)/2/rish_dim)%rish_dim)]
            #center = list_of_states_R[int(((index-index%2)/2*rish_dim)%rish_dim)]

            return center+right+charge
        
        else:
            right = list_of_states_L[int(index%rish_dim)]
            center = list_of_states_R[int(((index-index%rish_dim)/rish_dim)%rish_dim)]   
            
            return center+right

    elif pos%4 == 2:
        
        center = list_of_states_L[int(index%rish_dim)]
        left = list_of_states_R[int(((index-index%rish_dim)/rish_dim)%rish_dim)]

        return left+center
    
    elif pos%4 == 3:
        if charge%2 == 1:
        
            charge = list_of_states_ch[int(index%2)]
            center = list_of_states_R[int(((index-index%2)/2)%rish_dim)]
            left = list_of_states_R[int(((index-index%2)/2/rish_dim)%rish_dim)]

            return left+center+charge
        else:
            center = list_of_states_R[int(index%rish_dim)]
            left = list_of_states_R[int(((index-index%rish_dim)/rish_dim)%rish_dim)]

            return left+center           
    

In [35]:
for i in range(rish_dim**2*2):
    print(index_to_string_edge(i,1,1))

00r
00g
0pr
0pg
0p1r
0p1g
0p2r
0p2g
0rr
0rg
0gr
0gg
p0r
p0g
ppr
ppg
pp1r
pp1g
pp2r
pp2g
prr
prg
pgr
pgg
p10r
p10g
p1pr
p1pg
p1p1r
p1p1g
p1p2r
p1p2g
p1rr
p1rg
p1gr
p1gg
p20r
p20g
p2pr
p2pg
p2p1r
p2p1g
p2p2r
p2p2g
p2rr
p2rg
p2gr
p2gg
r0r
r0g
rpr
rpg
rp1r
rp1g
rp2r
rp2g
rrr
rrg
rgr
rgg
g0r
g0g
gpr
gpg
gp1r
gp1g
gp2r
gp2g
grr
grg
ggr
ggg


In [36]:
eigenval_ul,eigenvec_ul = np.linalg.eig(gauss_ul)
eigenval_ur,eigenvec_ur = np.linalg.eig(gauss_ur)
eigenval_dl,eigenvec_dl = np.linalg.eig(gauss_dl)
eigenval_dr,eigenvec_dr = np.linalg.eig(gauss_dr)


eigenval_ul_0,eigenvec_ul_0 = np.linalg.eig(gauss_ul_0)
eigenval_ur_0,eigenvec_ur_0 = np.linalg.eig(gauss_ur_0)

In [37]:
print(np.round(np.real(eigenval_ur[np.abs(eigenval_ur<=1e0)]),2))


[0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
#for i in range(64):
#    print(index_to_string_u(i))

In [39]:
for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_ul@CC_u_edge[0][i][j],CC_u_edge[0][i][j]@G_s_ul))
        print(np.allclose(G_r_ul@CC_u_edge[0][i][j],CC_u_edge[0][i][j]@G_r_ul))
        
for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_ur@CC_u_edge[1][i][j],CC_u_edge[1][i][j]@G_s_ur))
        print(np.allclose(G_r_ur@CC_u_edge[1][i][j],CC_u_edge[1][i][j]@G_r_ur))

for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_dl@CC_d_edge[0][i][j],CC_d_edge[0][i][j]@G_s_dl))
        print(np.allclose(G_r_dl@CC_d_edge[0][i][j],CC_d_edge[0][i][j]@G_r_dl))
        
for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_dr@CC_d_edge[1][i][j],CC_d_edge[1][i][j]@G_s_dr))
        print(np.allclose(G_r_dr@CC_d_edge[1][i][j],CC_d_edge[1][i][j]@G_r_dr))
        
        
        
for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_ul_0@CC_u_edge_0[0][i][j],CC_u_edge_0[0][i][j]@G_s_ul_0))
        print(np.allclose(G_r_ul_0@CC_u_edge_0[0][i][j],CC_u_edge_0[0][i][j]@G_r_ul_0))
        
for i in range(3):
    for j in range(3):
        print(np.allclose(G_s_ur_0@CC_u_edge_0[1][i][j],CC_u_edge_0[1][i][j]@G_s_ur_0))
        print(np.allclose(G_r_ur_0@CC_u_edge_0[1][i][j],CC_u_edge_0[1][i][j]@G_r_ur_0))
        


True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [40]:
for n in [0,2]:
    for i in range(3):
        for j in range(3):
            print(np.allclose(G_d_s@CC[n][i][j],CC[n][i][j]@G_d_s))
            print(np.allclose(G_d_r@CC[n][i][j],CC[n][i][j]@G_d_r))

for n in [1,3]:
    for i in range(3):
        for j in range(3):
            print(np.allclose(G_u_s@CC[n][i][j],CC[n][i][j]@G_u_s))
            print(np.allclose(G_u_r@CC[n][i][j],CC[n][i][j]@G_u_r))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [41]:
A = (G_u_s-np.eye(rish_dim**3))@(G_u_s-np.eye(rish_dim**3))

np.allclose(A,A.T.conj())

True

In [42]:
eigenval_u,eigenvec_u = np.linalg.eig(gauss_u)
eigenval_d,eigenvec_d = np.linalg.eig(gauss_d)

#for i in range(64):
#    print(np.real(eigenval_u[i]),np.imag(eigenval_u[i]))

print(np.round(np.real(eigenval_u[np.abs(eigenval_u<=1e0)]),2))
print(np.round(np.real(eigenval_d[np.abs(eigenval_d<=1e0)]),2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [43]:
inds_to_remove_u = []
inds_to_remove_d = []


for i in range(rish_dim**3):
    
    if (np.abs(eigenval_u[i])>1e-3):
        
        inds_to_remove_u.append(i)
        
    if (np.abs(eigenval_d[i])>1e-3):
        
        inds_to_remove_d.append(i)
        
        
inds_to_remove_ul = []
inds_to_remove_ur = []


for i in range(2*rish_dim**2):
    
    if (np.abs(eigenval_ul[i])>1e-3):
        
        inds_to_remove_ul.append(i)
        
    if (np.abs(eigenval_ur[i])>1e-3):
        
        inds_to_remove_ur.append(i)
        
        
inds_to_remove_dl = []
inds_to_remove_dr = []


for i in range(rish_dim**2):
    
    if (np.abs(eigenval_dl[i])>1e-3):
        
        inds_to_remove_dl.append(i)
        
    if (np.abs(eigenval_dr[i])>1e-3):
        
        inds_to_remove_dr.append(i)
        
        
        
        
inds_to_remove_ul_0 = []
inds_to_remove_ur_0 = []


for i in range(rish_dim**2):
    
    if (np.abs(eigenval_ul_0[i])>1e-3):
        
        inds_to_remove_ul_0.append(i)
        
    if (np.abs(eigenval_ur_0[i])>1e-3):
        
        inds_to_remove_ur_0.append(i)

In [44]:
numbers = [i for i in range(rish_dim**3)]
ginv_states_u = list(set(numbers) - set(inds_to_remove_u))
ginv_states_d = list(set(numbers) - set(inds_to_remove_d))

ginv_states_u.sort()
ginv_states_d.sort()


numbers_u = [i for i in range(2*rish_dim**2)]
ginv_states_ul = list(set(numbers_u) - set(inds_to_remove_ul))
ginv_states_ur = list(set(numbers_u) - set(inds_to_remove_ur))

ginv_states_ul.sort()
ginv_states_ur.sort()

numbers_d = [i for i in range(rish_dim**2)]
ginv_states_dl = list(set(numbers_d) - set(inds_to_remove_dl))
ginv_states_dr = list(set(numbers_d) - set(inds_to_remove_dr))

ginv_states_dl.sort()
ginv_states_dr.sort()


numbers_u_0 = [i for i in range(rish_dim**2)]
ginv_states_ul_0 = list(set(numbers_u_0) - set(inds_to_remove_ul_0))
ginv_states_ur_0 = list(set(numbers_u_0) - set(inds_to_remove_ur_0))

ginv_states_ul_0.sort()
ginv_states_ur_0.sort()

if N == 3:
    n_gi_st = 11 # number of gauge invariant states
if N == 4:
    n_gi_st = 28

In [45]:
for i in ginv_states_ul:
    print(i)
    for j in range(2*rish_dim**2):
        if np.abs(eigenvec_ul[:,i][j])>1e-2:
            print(i,eigenvec_ul[:,i][j],index_to_string_edge(j,1,1))
    

9
9 (0.7071067811865476+0j) 0rr
9 (0.7071067811865475+0j) 0gg
21
21 (0.7071067811865476+0j) prr
21 (-0.7071067811865475+0j) pgg
35
35 (0.7071067811865475+0j) p1rg
35 (0.7071067811865476+0j) p1gr
47
47 (-0.7071067811865475+0j) p2rg
47 (0.7071067811865476+0j) p2gr
53
53 (0.7071067811865476+0j) rp1r
53 (0.7071067811865475+0j) gp1g
55
55 (0.7071067811865476+0j) rp2r
55 (-0.7071067811865475+0j) gp2g
61
61 (0.7071067811865475+0j) r0g
61 (0.7071067811865476+0j) g0r
63
63 (-0.7071067811865475+0j) rpg
63 (0.7071067811865476+0j) gpr


In [46]:
for i in ginv_states_ur:
    print(i)
    for j in range(2*rish_dim**2):
        if np.abs(eigenvec_ur[:,i][j])>1e-2:
            print(i,eigenvec_ur[:,i][j],index_to_string_edge(j,3,1))    
    

11
11 (0.7071067811865475+0j) 0rg
11 (0.7071067811865476+0j) 0gr
23
23 (-0.7071067811865475+0j) prg
23 (0.7071067811865476+0j) pgr
33
33 (0.7071067811865476+0j) p1rr
33 (0.7071067811865475+0j) p1gg
45
45 (0.7071067811865476+0j) p2rr
45 (-0.7071067811865475+0j) p2gg
53
53 (0.7071067811865476+0j) rp1r
53 (0.7071067811865475+0j) gp1g
55
55 (0.7071067811865476+0j) rp2r
55 (-0.7071067811865475+0j) gp2g
61
61 (0.7071067811865475+0j) r0g
61 (0.7071067811865476+0j) g0r
63
63 (-0.7071067811865475+0j) rpg
63 (0.7071067811865476+0j) gpr


In [47]:
for i in ginv_states_ul_0:
    print(i)
    for j in range(rish_dim**2):
        if np.abs(eigenvec_ul_0[:,i][j])>1e-2:
            print(i,eigenvec_ul_0[:,i][j],index_to_string_edge(j,1,0))
    

13
13 (0.7071067811865476+0j) rr
13 (0.7071067811865475+0j) gg
20
20 (1+0j) 00
25
25 (1+0j) pp
30
30 (1+0j) p1p1
35
35 (1+0j) p2p2


In [48]:
for i in ginv_states_ur_0:
    print(i)
    for j in range(rish_dim**2):
        if np.abs(eigenvec_ur_0[:,i][j])>1e-2:
            print(i,eigenvec_ur_0[:,i][j],index_to_string_edge(j,3,0))

1
1 (0.7071067811865475+0j) rg
1 (0.7071067811865476+0j) gr
20
20 (1+0j) 00
25
25 (1+0j) pp
30
30 (1+0j) p1p1
35
35 (1+0j) p2p2


In [49]:
for i in ginv_states_dl:
    print(i)
    for j in range(rish_dim**2):
        if np.abs(eigenvec_dl[:,i][j])>1e-2:
            print(i,eigenvec_dl[:,i][j],index_to_string_edge(j,0,1))
    

1
1 (0.7071067811865475+0j) rg
1 (0.7071067811865476+0j) gr
20
20 (1+0j) 00
25
25 (1+0j) pp
30
30 (1+0j) p1p1
35
35 (1+0j) p2p2


In [50]:
for i in ginv_states_dr:
    print(i)
    for j in range(rish_dim**2):
        if np.abs(eigenvec_dr[:,i][j])>1e-2:
            print(i,eigenvec_dr[:,i][j],index_to_string_edge(j,2,1))
    

13
13 (0.7071067811865476+0j) rr
13 (0.7071067811865475+0j) gg
20
20 (1+0j) 00
25
25 (1+0j) pp
30
30 (1+0j) p1p1
35
35 (1+0j) p2p2


In [51]:
for i in ginv_states_u:
    print(i)
    for j in range(rish_dim**3):
        if np.abs(eigenvec_u[:,i][j])>1e-2:
            print(i,eigenvec_u[:,i][j],index_to_string_u(j))
    

3
3 (0.7071067811865476+0j) rpr
3 (-0.7071067811865475+0j) gpg
29
29 (0.7071067811865476+0j) 0rr
29 (0.7071067811865475+0j) 0gg
39
39 (0.7071067811865476+0j) rrp1
39 (0.7071067811865475+0j) ggp1
45
45 (0.7071067811865476+0j) rg0
45 (0.7071067811865475+0j) gr0
65
65 (0.7071067811865476+0j) prr
65 (-0.7071067811865475+0j) pgg
91
91 (0.7071067811865475+0j) rp1g
91 (0.7071067811865476+0j) gp1r
107
107 (0.7071067811865475+0j) p1rg
107 (0.7071067811865476+0j) p1gr
111
111 (-0.7071067811865475+0j) rp2g
111 (0.7071067811865476+0j) gp2r
115
115 (0.7071067811865476+0j) rgp
115 (-0.7071067811865475-0j) grp
127
127 (0.7071067811865476+0j) rrp2
127 (-0.7071067811865475-0j) ggp2
143
143 (-0.7071067811865475+0j) p2rg
143 (0.7071067811865476+0j) p2gr
149
149 (0.7071067811865476+0j) r0r
149 (0.7071067811865475+0j) g0g
152
152 (1+0j) 000
157
157 (1+0j) 0pp
162
162 (1+0j) 0p1p1
167
167 (1+0j) 0p2p2
169
169 (1+0j) p0p
172
172 (1+0j) pp0
179
179 (1+0j) pp1p2
182
182 (1+0j) pp2p1
186
186 (1+0j) p10p1
191
19

In [52]:
def RI_U(i):
    
    J = 0
    
    for j in range(rish_dim**3):
        if np.abs(eigenvec_u[:,i][j])>1e-2:
            J = j
            break
    return J

def RI_D(i):
    
    J = 0
    
    for j in range(rish_dim**3):
        if np.abs(eigenvec_d[:,i][j])>1e-2:
            J = j
            break
    return J


def RI_edge(i,pos,charge):
    
    J = 0
    
    if pos%4 == 0:
    
        for j in range(rish_dim**2):
            if np.abs(eigenvec_dl[:,i][j])>1e-2:
                J = j
                break
                
    elif pos%4 == 1:
        if charge%2 == 1:
    
            for j in range(2*rish_dim**2):
                if np.abs(eigenvec_ul[:,i][j])>1e-2:
                    J = j
                    break
        else:
            for j in range(rish_dim**2):
                if np.abs(eigenvec_ul_0[:,i][j])>1e-2:
                    J = j
                    break            

    elif pos%4 == 2:
    
        for j in range(rish_dim**2):
            if np.abs(eigenvec_dr[:,i][j])>1e-2:
                J = j
                break                
    
    elif pos%4 == 3:
        if charge%2 == 1:
    
            for j in range(2*rish_dim**2):
                if np.abs(eigenvec_ur[:,i][j])>1e-2:
                    J = j
                    break
        else:
            for j in range(rish_dim**2):
                if np.abs(eigenvec_ur_0[:,i][j])>1e-2:
                    J = j
                    break
                
    return J

In [53]:
Ds = []

In [90]:
if N == 3:
        alpha = np.array([-1,10,0])
        list_efield = [0.5*alpha[0],0.5*alpha[1],0.5*alpha[2],0.5*alpha[2]]
elif N == 4:
        alpha = np.array([-1,10,10,10,0])
        list_efield = [0.5*alpha[0],0.5*alpha[1],0.5*alpha[2],0.5*alpha[3],0.5*alpha[4],0.5*alpha[4]]

#print(list_efield)

E_field_u = np.diag(np.array([list_efield[int(RI_U(i)%rish_dim)]+list_efield[int(((RI_U(i)-RI_U(i)%rish_dim)/rish_dim)%rish_dim)]+list_efield[int(((RI_U(i)-RI_U(i)%rish_dim)/rish_dim**2)%rish_dim)] for i in ginv_states_u]))
E_field_d = np.diag(np.array([list_efield[int(RI_D(i)%rish_dim)]+list_efield[int(((RI_D(i)-RI_D(i)%rish_dim)/rish_dim)%rish_dim)]+list_efield[int(((RI_D(i)-RI_D(i)%rish_dim)/rish_dim**2)%rish_dim)] for i in ginv_states_d]))


E_field_dl = np.diag(np.array([list_efield[int(RI_edge(i,0,1)%rish_dim)]+list_efield[int(((RI_edge(i,0,1)-RI_edge(i,0,1)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_dl]))

E_field_ul = np.diag(np.array([list_efield[int(((RI_edge(i,1,1)-RI_edge(i,1,1)%2)/2)%rish_dim)]+list_efield[int(((RI_edge(i,1,1)-RI_edge(i,1,1)%2)/2/rish_dim)%rish_dim)] for i in ginv_states_ul]))

E_field_dr = np.diag(np.array([list_efield[int(RI_edge(i,2,1)%rish_dim)]+list_efield[int(((RI_edge(i,2,1)-RI_edge(i,2,1)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_dr]))

E_field_ur = np.diag(np.array([list_efield[int(((RI_edge(i,3,1)-RI_edge(i,3,1)%2)/2)%rish_dim)]+list_efield[int(((RI_edge(i,3,1)-RI_edge(i,3,1)%2)/2/rish_dim)%rish_dim)] for i in ginv_states_ur]))


E_field_ul_0 = np.diag(np.array([list_efield[int(RI_edge(i,1,0)%rish_dim)]+list_efield[int(((RI_edge(i,1,0)-RI_edge(i,1,0)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_ul_0]))

E_field_ur_0 = np.diag(np.array([list_efield[int(RI_edge(i,3,0)%rish_dim)]+list_efield[int(((RI_edge(i,3,0)-RI_edge(i,3,0)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_ur_0]))

E_field_ur

array([[-0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  5. ,  0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  5. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  5. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  5. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  5. ]])

In [93]:
file_input = []
n_gi_edge_sts = len(ginv_states_ur_0)  # number of gauge invariant states on the edge sites
n_gi_edge_chr = len(ginv_states_ur)    # number of gauge invariant states on charghed edge sites 


for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(E_field_u[i][j]),10),round(np.imag(E_field_u[i][j]),10)))

np.savetxt("efields/efield_u.txt", file_input)   # write


file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(E_field_d[i][j]),10),round(np.imag(E_field_d[i][j]),10)))

np.savetxt("efields/efield_d.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(E_field_ul[i][j]),10),round(np.imag(E_field_ul[i][j]),10)))

np.savetxt("efields/efield_ul.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(E_field_ur[i][j]),10),round(np.imag(E_field_ur[i][j]),10)))

np.savetxt("efields/efield_ur.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(E_field_dl[i][j]),10),round(np.imag(E_field_dl[i][j]),10)))

np.savetxt("efields/efield_dl.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(E_field_dr[i][j]),10),round(np.imag(E_field_dr[i][j]),10)))

np.savetxt("efields/efield_dr.txt", file_input)   # write


file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(E_field_ul_0[i][j]),10),round(np.imag(E_field_ul_0[i][j]),10)))

np.savetxt("efields/efield_ul_0.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(E_field_ur_0[i][j]),10),round(np.imag(E_field_ur_0[i][j]),10)))

np.savetxt("efields/efield_ur_0.txt", file_input)   # write

In [94]:
if N == 3:
        list_match_ru = [1,2,-1,-1]
        list_match_ld = [1,1/2,-1,-1]
elif N == 4:
        list_match_ru = [1,-1,2  ,3  ,  4,  4]
        list_match_ld = [1,-1,1/2,1/3,1/4,1/4]

D_R_u = np.diag(np.array([list_match_ru[(int(RI_U(i)%rish_dim))] for i in ginv_states_u]))
#print(np.array([list_match_ru[(int(RI_U(i)%rish_dim))] for i in ginv_states_u]))
#print(D_R_u)

#D_R_u = sparse.csc_matrix(D_R_u)

D_L_u = np.diag(np.array([list_match_ld[int(((RI_U(i)-RI_U(i)%rish_dim)/rish_dim**2)%rish_dim)] for i in ginv_states_u]))
#print(np.array([list_match_ld[int(((RI_U(i)-RI_U(i)%rish_dim)/rish_dim**2)%rish_dim)] for i in ginv_states_u]))

#D_L_u = sparse.csc_matrix(D_L_u)


D_C_u = np.diag(np.array([list_match_ru[int(((RI_U(i)-RI_U(i)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_u]))

#D_C_u = sparse.csc_matrix(D_C_u)

#DD_L_u = np.diag(np.array([1,0,1,1,1,1,1,0,0,1,1]))

#DD_L_u = sparse.csc_matrix(DD_L_u)

#DD_R_u = np.diag(np.array([0,1,1,1,1,1,1,0,1,1,0]))

#DD_R_u = sparse.csc_matrix(DD_R_u)


D_R_ul = np.diag(np.array([list_match_ru[int(((RI_edge(i,1,1)-RI_edge(i,1,1)%2)/2)%rish_dim)] for i in ginv_states_ul]))

D_C_ul = np.diag(np.array([list_match_ru[int(((RI_edge(i,1,1)-RI_edge(i,1,1)%2)/2/rish_dim)%rish_dim)] for i in ginv_states_ul]))


D_C_ur = np.diag(np.array([list_match_ru[int(((RI_edge(i,3,1)-RI_edge(i,3,1)%2)/2)%rish_dim)] for i in ginv_states_ur]))

D_L_ur = np.diag(np.array([list_match_ld[int(((RI_edge(i,3,1)-RI_edge(i,3,1)%2)/2/rish_dim)%rish_dim)] for i in ginv_states_ur]))



D_R_dl = np.diag(np.array([list_match_ru[int(RI_edge(i,0,1)%rish_dim)] for i in ginv_states_dl]))

D_C_dl = np.diag(np.array([list_match_ld[int(((RI_edge(i,0,1)-RI_edge(i,0,1)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_dl]))



D_C_dr = np.diag(np.array([list_match_ld[int(((RI_edge(i,2,1)-RI_edge(i,2,1)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_dr]))

D_L_dr = np.diag(np.array([list_match_ld[int(RI_edge(i,2,1)%rish_dim)] for i in ginv_states_dr]))



D_R_ul_0 = np.diag(np.array([list_match_ru[int(RI_edge(i,1,0)%rish_dim)] for i in ginv_states_ul_0]))

D_C_ul_0 = np.diag(np.array([list_match_ru[int(((RI_edge(i,1,0)-RI_edge(i,1,0)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_ul_0]))



D_C_ur_0 = np.diag(np.array([list_match_ru[int(((RI_edge(i,3,0)-RI_edge(i,3,0)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_ur_0]))

D_L_ur_0 = np.diag(np.array([list_match_ld[int(RI_edge(i,3,0)%rish_dim)] for i in ginv_states_ur_0]))



print(D_R_dl)
print(D_R_ul)



[[ 4  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0  0  2  0]
 [ 0  0  0  0  3]]
[[ 4  0  0  0  0  0  0  0]
 [ 0  4  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0]
 [ 0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 -1]]


In [95]:
gauss_ul_ginv = np.delete(eigenvec_ul.T.conj()@gauss_ul@eigenvec_ul, inds_to_remove_ul, axis=0)
gauss_ul_ginv = np.delete(gauss_ul_ginv, inds_to_remove_ul, axis=1)

print(np.round(gauss_ul_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [96]:
gauss_ur_ginv = np.delete(eigenvec_ur.T.conj()@gauss_ur@eigenvec_ur, inds_to_remove_ur, axis=0)
gauss_ur_ginv = np.delete(gauss_ur_ginv, inds_to_remove_ur, axis=1)

print(np.round(gauss_ur_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [97]:
gauss_ul_ginv_0 = np.delete(eigenvec_ul_0.T.conj()@gauss_ul_0@eigenvec_ul_0, inds_to_remove_ul_0, axis=0)
gauss_ul_ginv_0 = np.delete(gauss_ul_ginv_0, inds_to_remove_ul_0, axis=1)

print(np.round(gauss_ul_ginv_0,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [98]:
gauss_ur_ginv_0 = np.delete(eigenvec_ur_0.T.conj()@gauss_ur_0@eigenvec_ur_0, inds_to_remove_ur_0, axis=0)
gauss_ur_ginv_0 = np.delete(gauss_ur_ginv_0, inds_to_remove_ur_0, axis=1)

print(np.round(gauss_ur_ginv_0,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [99]:
gauss_dl_ginv = np.delete(eigenvec_dl.T.conj()@gauss_dl@eigenvec_dl, inds_to_remove_dl, axis=0)
gauss_dl_ginv = np.delete(gauss_dl_ginv, inds_to_remove_dl, axis=1)

print(np.round(gauss_dl_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [100]:
gauss_dr_ginv = np.delete(eigenvec_dr.T.conj()@gauss_dr@eigenvec_dr, inds_to_remove_dr, axis=0)
gauss_dr_ginv = np.delete(gauss_dr_ginv, inds_to_remove_dr, axis=1)

print(np.round(gauss_dr_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


In [101]:
gauss_u_ginv = np.delete(eigenvec_u.T.conj()@gauss_u@eigenvec_u, inds_to_remove_u, axis=0)
gauss_u_ginv = np.delete(gauss_u_ginv, inds_to_remove_u, axis=1)


print(np.round(gauss_u_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 

In [102]:
for i in ginv_states_d:
    print(i)
    for j in range(rish_dim**3):
        if np.abs(eigenvec_d[:,i][j])>1e-2:
            print(i,eigenvec_d[:,i][j],index_to_string_d(j))
    

3
3 (0.7071067811865476+0j) rpr
3 (-0.7071067811865475+0j) gpg
35
35 (0.7071067811865475+0j) 0rg
35 (0.7071067811865476+0j) 0gr
37
37 (0.7071067811865476+0j) rr0
37 (0.7071067811865475+0j) gg0
49
49 (0.7071067811865476+0j) rgp1
49 (0.7071067811865475+0j) grp1
71
71 (-0.7071067811865475+0j) prg
71 (0.7071067811865476+0j) pgr
91
91 (0.7071067811865475+0j) rp1g
91 (0.7071067811865476+0j) gp1r
101
101 (0.7071067811865476+0j) p1rr
101 (0.7071067811865475+0j) p1gg
111
111 (-0.7071067811865475+0j) rp2g
111 (0.7071067811865476+0j) gp2r
117
117 (0.7071067811865476+0j) rgp2
117 (-0.7071067811865475-0j) grp2
123
123 (0.7071067811865476+0j) rrp
123 (-0.7071067811865475-0j) ggp
137
137 (0.7071067811865476+0j) p2rr
137 (-0.7071067811865475+0j) p2gg
149
149 (0.7071067811865476+0j) r0r
149 (0.7071067811865475+0j) g0g
152
152 (1+0j) 000
157
157 (1+0j) 0pp
162
162 (1+0j) 0p1p1
167
167 (1+0j) 0p2p2
169
169 (1+0j) p0p


172
172 (1+0j) pp0
179
179 (1+0j) pp1p2
182
182 (1+0j) pp2p1
186
186 (1+0j) p10p1
191
191 (1+0j) p1pp2
192
192 (1+0j) p1p10
197
197 (1+0j) p1p2p
203
203 (1+0j) p20p2
206
206 (1+0j) p2pp1
209
209 (1+0j) p2p1p
212
212 (1+0j) p2p20


In [103]:
D_R_d = np.diag(np.array([list_match_ru[(int(RI_D(i)%rish_dim))] for i in ginv_states_d]))
#print(D_R_d)

#D_R_d = sparse.csc_matrix(D_R_d)

D_L_d = np.diag(np.array([list_match_ld[int(((RI_D(i)-RI_D(i)%rish_dim)/rish_dim**2)%rish_dim)] for i in ginv_states_d]))


#D_L_d = sparse.csc_matrix(D_L_d)


D_C_d = np.diag(np.array([list_match_ld[int(((RI_D(i)-RI_D(i)%rish_dim)/rish_dim)%rish_dim)] for i in ginv_states_d]))

#D_C_d = sparse.csc_matrix(D_C_d)


#DD_L_d = np.diag(np.array([1,0,1,1,1,1,1,0,0,1,1]))

#DD_L_d = sparse.csc_matrix(DD_L_d)

#DD_R_d = np.diag(np.array([0,1,1,1,1,1,1,0,1,1,0]))

#DD_R_d = sparse.csc_matrix(DD_R_d)




In [104]:
gauss_d_ginv = np.delete(eigenvec_d.T.conj()@gauss_u@eigenvec_d, inds_to_remove_d, axis=0)
gauss_d_ginv = np.delete(gauss_d_ginv, inds_to_remove_d, axis=1)


print(np.round(gauss_u_ginv,2))

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j
  0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 

In [105]:
#np.allclose(eigenvec_u.T.conj()@gauss_u@eigenvec_u,np.diag(eigenval_u))

In [106]:
CC_transf = np.zeros((4,N,N,rish_dim**3,rish_dim**3),dtype = complex)

CC_ginv = np.zeros((4,N,N,n_gi_st,n_gi_st),dtype = complex)

for n in [0,2]:
    for i in range(N):
        for j in range(N):
            CC_transf[n][i][j] = eigenvec_d.T.conj()@CC[n][i][j]@eigenvec_d
            mat = np.delete(CC_transf[n][i][j], inds_to_remove_d, axis=0)
            CC_ginv[n][i][j] = np.delete(mat, inds_to_remove_d, axis=1)

for n in [1,3]:
    for i in range(N):
        for j in range(N):
            CC_transf[n][i][j] = eigenvec_u.T.conj()@CC[n][i][j]@eigenvec_u
            mat = np.delete(CC_transf[n][i][j], inds_to_remove_u, axis=0)
            CC_ginv[n][i][j] = np.delete(mat, inds_to_remove_u, axis=1)

In [107]:
CC_transf_u_edge = np.zeros((2,N,N,2*rish_dim**2,2*rish_dim**2),dtype = complex)
CC_ginv_u_edge = np.zeros((2,N,N,len(ginv_states_ur),len(ginv_states_ur)),dtype = complex)


for i in range(N):
    for j in range(N):
        CC_transf_u_edge[0][i][j] = eigenvec_ul.T.conj()@CC_u_edge[0][i][j]@eigenvec_ul
        mat = np.delete(CC_transf_u_edge[0][i][j], inds_to_remove_ul, axis=0)
        CC_ginv_u_edge[0][i][j] = np.delete(mat, inds_to_remove_ul, axis=1)

for i in range(N):
    for j in range(N):
        CC_transf_u_edge[1][i][j] = eigenvec_ur.T.conj()@CC_u_edge[1][i][j]@eigenvec_ur
        mat = np.delete(CC_transf_u_edge[1][i][j], inds_to_remove_ur, axis=0)
        CC_ginv_u_edge[1][i][j] = np.delete(mat, inds_to_remove_ur, axis=1)
        


CC_transf_d_edge = np.zeros((2,N,N,rish_dim**2,rish_dim**2),dtype = complex)
CC_ginv_d_edge = np.zeros((2,N,N,len(ginv_states_dr),len(ginv_states_dr)),dtype = complex)

for i in range(N):
    for j in range(N):
        CC_transf_d_edge[0][i][j] = eigenvec_dl.T.conj()@CC_d_edge[0][i][j]@eigenvec_dl
        mat = np.delete(CC_transf_d_edge[0][i][j], inds_to_remove_dl, axis=0)
        CC_ginv_d_edge[0][i][j] = np.delete(mat, inds_to_remove_dl, axis=1)

for i in range(N):
    for j in range(N):
        CC_transf_d_edge[1][i][j] = eigenvec_dr.T.conj()@CC_d_edge[1][i][j]@eigenvec_dr
        mat = np.delete(CC_transf_d_edge[1][i][j], inds_to_remove_dr, axis=0)
        CC_ginv_d_edge[1][i][j] = np.delete(mat, inds_to_remove_dr, axis=1)
        


CC_transf_u_edge_0 = np.zeros((2,N,N,rish_dim**2,rish_dim**2),dtype = complex)
CC_ginv_u_edge_0 = np.zeros((2,N,N,len(ginv_states_ur_0),len(ginv_states_ur_0)),dtype = complex)


for i in range(N):
    for j in range(N):
        CC_transf_u_edge_0[0][i][j] = eigenvec_ul_0.T.conj()@CC_u_edge_0[0][i][j]@eigenvec_ul_0
        mat = np.delete(CC_transf_u_edge_0[0][i][j], inds_to_remove_ul_0, axis=0)
        CC_ginv_u_edge_0[0][i][j] = np.delete(mat, inds_to_remove_ul_0, axis=1)

for i in range(N):
    for j in range(N):
        CC_transf_u_edge_0[1][i][j] = eigenvec_ur_0.T.conj()@CC_u_edge_0[1][i][j]@eigenvec_ur_0
        mat = np.delete(CC_transf_u_edge_0[1][i][j], inds_to_remove_ur_0, axis=0)
        CC_ginv_u_edge_0[1][i][j] = np.delete(mat, inds_to_remove_ur_0, axis=1)

In [108]:
pen = 10

if N == 3:
    pl_dim = 15
elif N == 4:
    pl_dim = 40

plaquette = np.zeros((pl_dim**2,pl_dim**2),dtype = complex)
plaquette = sparse.csc_matrix(plaquette)


for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]
                
                A = sparse.csc_matrix(CC_ginv_d_edge[0][i_c][j])
                B = sparse.csc_matrix(CC_ginv_u_edge[0][i][l])
                C = sparse.csc_matrix(CC_ginv_d_edge[1][j_c][k])
                D = sparse.csc_matrix(CC_ginv_u_edge[1][l_c][k_c])
                                
                plaquette -= sparse.kron(sparse.kron(A,B),sparse.kron(C,D))



    
    
plaquette += pen*(sparse.kron(sparse.kron(D_C_dl,D_C_ul),sparse.eye(pl_dim))-sparse.eye(pl_dim**2))**2

plaquette += pen*(sparse.kron(sparse.kron(D_R_dl,sparse.eye(len(ginv_states_ur))),sparse.kron(D_L_dr,sparse.eye(len(ginv_states_ur))))-sparse.eye(pl_dim**2))**2

plaquette += pen*(sparse.kron(sparse.eye(pl_dim),sparse.kron(D_C_dr,D_C_ur))-sparse.eye(pl_dim**2))**2

plaquette += pen*(sparse.kron(sparse.kron(sparse.eye(len(ginv_states_ur_0)),D_R_ul),sparse.kron(sparse.eye(len(ginv_states_ur_0)),D_L_ur))-sparse.eye(pl_dim**2))**2



print(np.shape(plaquette))
        
    
np.allclose(plaquette.toarray(),plaquette.toarray().T.conj())
            

(1600, 1600)


True

In [109]:
from scipy.sparse import linalg

eigenval, eigenvec = linalg.eigsh(plaquette, k=10,which = "SA")
print(eigenval)

[-2.          0.73611111  0.62421902  1.0387561   0.62421902  1.23611111
  1.11111111  1.11111111  1.11111111  1.11111111]


In [110]:
pen = 10
n_gi_edge_sts = len(ginv_states_ur_0)  # number of gauge invariant states on the edge sites
n_gi_edge_chr = len(ginv_states_ur)    # number of gauge invariant states on charghed edge sites 

plaquette = np.zeros((n_gi_edge_sts**4,n_gi_edge_sts**4),dtype = complex)

plaquette = sparse.csc_matrix(plaquette)


for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]
                
                A = sparse.csc_matrix(CC_ginv_d_edge[0][i_c][j])
                B = sparse.csc_matrix(CC_ginv_u_edge_0[0][i][l])
                C = sparse.csc_matrix(CC_ginv_d_edge[1][j_c][k])
                D = sparse.csc_matrix(CC_ginv_u_edge_0[1][l_c][k_c])
                                
                plaquette -= sparse.kron(sparse.kron(A,B),sparse.kron(C,D))



    
    
plaquette += pen*(sparse.kron(sparse.kron(D_C_dl,D_C_ul_0),sparse.eye(n_gi_edge_sts**2))-sparse.eye(n_gi_edge_sts**4))**2



plaquette += pen*(sparse.kron(sparse.kron(D_R_dl,sparse.eye(n_gi_edge_sts)),sparse.kron(D_L_dr,sparse.eye(n_gi_edge_sts)))-sparse.eye(n_gi_edge_sts**4))**2



plaquette += pen*(sparse.kron(sparse.eye(n_gi_edge_sts**2),sparse.kron(D_C_dr,D_C_ur_0))-sparse.eye(n_gi_edge_sts**4))**2



plaquette += pen*(sparse.kron(sparse.kron(sparse.eye(n_gi_edge_sts),D_R_ul_0),sparse.kron(sparse.eye(n_gi_edge_sts),D_L_ur_0))-sparse.eye(n_gi_edge_sts**4))**2



print(np.shape(plaquette))
        
    
np.allclose(plaquette.toarray(),plaquette.toarray().T.conj())
            

(625, 625)


True

In [111]:
eigenval, eigenvec = scipy.linalg.eigh(plaquette.toarray())
print(eigenval)

[ -2.           0.           0.           0.           0.62421902
   0.62421902   0.62421902   0.62421902   0.73611111   0.73611111
   2.           2.22222222   2.22222222   2.22222222   2.22222222
   2.47222222   2.73611111   2.73611111   2.8480032    2.8480032
   2.8480032    2.8480032    3.47222222   3.61111111   3.61111111
   3.61111111   3.61111111   4.23611111   4.23611111   4.23611111
   4.23611111   4.47222222   4.72222222   4.72222222   4.72222222
   4.72222222   4.93362702   4.93362702   4.93362702   4.93362702
   5.           5.           5.           5.           5.
   5.           5.           5.           5.34722222   5.34722222
   5.625        5.625        5.625        5.625        7.22222222
   7.22222222   7.22222222   7.22222222   7.22222222   8.05555556
   8.05555556   8.05555556   8.05555556   8.88888889   8.88888889
   8.88888889   8.88888889   9.44444444   9.44444444   9.44444444
   9.44444444  10.          10.          10.06944444  10.06944444
  10.13888889  10.3

In [112]:
for i in range(len(eigenvec[:,0])):
    
    if np.abs(eigenvec[:,0][i])>1e-6:
        #print(i,eigenvec[:,0][i])
        
        print(i,i%n_gi_edge_sts,(int((i-i%n_gi_edge_sts)/n_gi_edge_sts))%n_gi_edge_sts,(int((i-i%n_gi_edge_sts)/n_gi_edge_sts**2))%n_gi_edge_sts,(int((i-i%n_gi_edge_sts)/n_gi_edge_sts**3))%n_gi_edge_sts)

0 0 0 0 0
156 1 1 1 1
312 2 2 2 2
468 3 3 3 3
624 4 4 4 4


In [113]:
pen = 10

plaquette = sparse.csc_matrix((n_gi_st**4, n_gi_st**4), dtype=complex)

for i in range(N):
    for j in range(N):
        for k in range(N):
            for l in range(N):
                
                i_c = liste[i]
                j_c = liste[j]
                k_c = liste[k]
                l_c = liste[l]
                
                
                A = sparse.csc_matrix(CC_ginv[0][i_c][j])
                B = sparse.csc_matrix(CC_ginv[1][i][l])
                C = sparse.csc_matrix(CC_ginv[2][j_c][k])
                D = sparse.csc_matrix(CC_ginv[3][l_c][k_c])

                                
                plaquette -= sparse.kron(sparse.kron(A,B),sparse.kron(C,D))
    
plaquette += pen*(sparse.kron(sparse.kron(D_C_d,D_C_u),sparse.eye(n_gi_st**2))-sparse.eye(n_gi_st**4))**2

plaquette += pen*(sparse.kron(sparse.kron(D_R_d,sparse.eye(n_gi_st)),sparse.kron(D_L_d,sparse.eye(n_gi_st)))-sparse.eye(n_gi_st**4))**2

plaquette += pen*(sparse.kron(sparse.eye(n_gi_st**2),sparse.kron(D_C_d,D_C_u))-sparse.eye(n_gi_st**4))**2

plaquette += pen*(sparse.kron(sparse.kron(sparse.eye(n_gi_st),D_R_u),sparse.kron(sparse.eye(n_gi_st),D_L_u))-sparse.eye(n_gi_st**4))**2


#plaquette += pen*sparse.kron(DD_L_d,sparse.eye(11**3))

#plaquette += pen*sparse.kron(sparse.kron(np.eye(11),DD_L_u),np.eye(11**2))

#plaquette += pen*sparse.kron(np.eye(11**2),sparse.kron(DD_R_d,np.eye(11)))

#plaquette += pen*sparse.kron(sparse.eye(11**3),DD_R_u)


print(np.shape(plaquette))
        
def is_hermitian_sparse(A, tol=1e-12):
    """
    Check if a sparse matrix A is Hermitian using sparse operations only.

    Parameters:
    - A: scipy.sparse matrix (should be square and complex)
    - tol: tolerance for numerical equality

    Returns:
    - True if A ≈ A^† (Hermitian), False otherwise
    """

    diff = A - A.getH()  # A.getH() = A.T.conj()
    max_abs_diff = abs(diff).max()

    return max_abs_diff < tol
    
print(is_hermitian_sparse(plaquette))
            

(614656, 614656)
True


In [114]:
psi_plaquette = np.zeros(n_gi_st**4,dtype = complex)

#index = 0 2 1 1

index = 0*n_gi_st**0 + 2*n_gi_st**1 + 1*n_gi_st**2 + 1*n_gi_st**3
#index = 6*n_gi_st**0 + 2*n_gi_st**1 + 3*n_gi_st**2 + 1*n_gi_st**3
psi_plaquette[index] = 2
#psi_plaquette[index] = (-0.21582990440024966+0.7874542012290429j)


index = 7*n_gi_st**0 + 7*n_gi_st**1 + 7*n_gi_st**2 + 7*n_gi_st**3
#index = 9*n_gi_st**0 + 7*n_gi_st**1 + 9*n_gi_st**2 + 7*n_gi_st**3
psi_plaquette[index] = 1
#psi_plaquette[index] = (0.10791495220012474-0.39372710061452154j)

index = 10*n_gi_st**0 + 10*n_gi_st**1 + 8*n_gi_st**2 + 8*n_gi_st**3
#index = 8*n_gi_st**0 + 10*n_gi_st**1 + 10*n_gi_st**2 + 8*n_gi_st**3
psi_plaquette[index] = 1
#psi_plaquette[index] = (0.10791495220012509-0.3937271006145207j)

norm = np.sqrt(np.abs(np.conj(psi_plaquette)@psi_plaquette))
print(norm)

psi_plaquette = psi_plaquette/norm

norm = np.sqrt(np.abs(np.conj(psi_plaquette)@psi_plaquette))
print(norm)

2.449489742783178
1.0


In [115]:
print(np.real(np.conj(psi_plaquette)@plaquette@psi_plaquette))

13.379629629629633


In [116]:
from scipy.sparse import linalg

eigenval, eigenvec = linalg.eigsh(plaquette, k=1,which = "SA")
print(eigenval)

[-2.]


In [117]:
for i in range(len(eigenvec[:,0])):
    
    if np.abs(eigenvec[:,0][i])>1e-10:
        #print(i,eigenvec[:,0][i])
        
        print(i,eigenvec[:,0][i],i%n_gi_st,(int((i-i%n_gi_st)/n_gi_st))%n_gi_st,(int((i-i%n_gi_st)/n_gi_st**2))%n_gi_st,(int((i-i%n_gi_st)/n_gi_st**3))%n_gi_st)

0 (0.027005222275126108-0.01542008926951481j) 0 0 0 0
58 (-0.01522301026450231-0.024661487162997386j) 2 2 0 0
59 (0.009512333813991726+0.019376974416860187j) 3 2 0 0
64 (-0.01323608175612578+0.035515309134979384j) 8 2 0 0
65 (-0.03186621383915367+0.0073457352963020245j) 9 2 0 0
86 (0.017271245505564237-0.00013882500556455766j) 2 3 0 0
87 (0.014793184479001109+0.0008472957912195411j) 3 3 0 0
92 (0.01820149585856447+0.010058619467133904j) 8 3 0 0
93 (0.0007079109240471111-0.005421103638740075j) 9 3 0 0
145 (-0.017103005400291218-0.012730163520286036j) 5 5 0 0
203 (0.00831664940942707+0.012429201959882839j) 7 7 0 0
226 (0.005679984782144492+0.0004484475974875548j) 2 8 0 0
227 (-0.024706954951781025-0.017488371459332974j) 3 8 0 0
232 (-0.017637647084653384+0.007671449923632039j) 8 8 0 0
233 (0.0026263593928622757-0.015063874829837405j) 9 8 0 0
254 (0.0311458246561227+0.025250093661429274j) 2 9 0 0
255 (0.025052764800770698-0.005374367985602951j) 3 9 0 0
260 (-0.017789755634500363+0.0638082

In [118]:
for nn in [0,1]:
    for a in range(N):
        for b in range(N):
        
            file_input = []


            for i in range(n_gi_edge_chr):
                for j in range(n_gi_edge_chr):
                    file_input.append((i+1,j+1,round(np.real(CC_ginv_u_edge[nn][a][b][i][j]),10),round(np.imag(CC_ginv_u_edge[nn][a][b][i][j]),10)))

            np.savetxt("corner_operators/corner_u_edge_"+str(nn)+"_"+str(a)+"_"+str(b)+".txt", file_input)   # write

for nn in [0,1]:
    for a in range(N):
        for b in range(N):
        
            file_input = []


            for i in range(n_gi_edge_sts):
                for j in range(n_gi_edge_sts):
                    file_input.append((i+1,j+1,round(np.real(CC_ginv_d_edge[nn][a][b][i][j]),10),round(np.imag(CC_ginv_d_edge[nn][a][b][i][j]),10)))

            np.savetxt("corner_operators/corner_d_edge_"+str(nn)+"_"+str(a)+"_"+str(b)+".txt", file_input)   # write

            
for nn in [0,1]:
    for a in range(N):
        for b in range(N):
        
            file_input = []


            for i in range(n_gi_edge_sts):
                for j in range(n_gi_edge_sts):
                    file_input.append((i+1,j+1,round(np.real(CC_ginv_u_edge_0[nn][a][b][i][j]),10),round(np.imag(CC_ginv_u_edge_0[nn][a][b][i][j]),10)))

            np.savetxt("corner_operators/corner_u_edge_0_"+str(nn)+"_"+str(a)+"_"+str(b)+".txt", file_input)   # write


In [119]:
file_input = []

for nn in range(4):
    for a in range(N):
        for b in range(N):
        
            file_input = []


            for i in range(n_gi_st):
                for j in range(n_gi_st):
                    file_input.append((i+1,j+1,round(np.real(CC_ginv[nn][a][b][i][j]),10),round(np.imag(CC_ginv[nn][a][b][i][j]),10)))

            np.savetxt("corner_operators/corner_"+str(nn)+"_"+str(a)+"_"+str(b)+".txt", file_input)   # write



In [120]:
file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_R_u[i][j]),10),round(np.imag(D_R_u[i][j]),10)))
        
np.savetxt("constraints/D_R_u.txt", file_input)   # write

file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_L_u[i][j]),10),round(np.imag(D_L_u[i][j]),10)))
        
np.savetxt("constraints/D_L_u.txt", file_input)   # write

file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_C_u[i][j]),10),round(np.imag(D_C_u[i][j]),10)))
        
np.savetxt("constraints/D_C_u.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(D_R_ul[i][j]),10),round(np.imag(D_R_ul[i][j]),10)))
        
np.savetxt("constraints/D_R_ul.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(D_C_ul[i][j]),10),round(np.imag(D_C_ul[i][j]),10)))
        
np.savetxt("constraints/D_C_ul.txt", file_input)   # write

file_input = []


for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_R_ul_0[i][j]),10),round(np.imag(D_R_ul_0[i][j]),10)))
        
np.savetxt("constraints/D_R_ul_0.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_C_ul_0[i][j]),10),round(np.imag(D_C_ul_0[i][j]),10)))
        
np.savetxt("constraints/D_C_ul_0.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(D_C_ur[i][j]),10),round(np.imag(D_C_ur[i][j]),10)))
        
np.savetxt("constraints/D_C_ur.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_chr):
    for j in range(n_gi_edge_chr):
        file_input.append((i+1,j+1,round(np.real(D_L_ur[i][j]),10),round(np.imag(D_L_ur[i][j]),10)))
        
np.savetxt("constraints/D_L_ur.txt", file_input)   # write

file_input = []


for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_C_ur_0[i][j]),10),round(np.imag(D_C_ur_0[i][j]),10)))
        
np.savetxt("constraints/D_C_ur_0.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_L_ur_0[i][j]),10),round(np.imag(D_L_ur_0[i][j]),10)))
        
np.savetxt("constraints/D_L_ur_0.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_R_dl[i][j]),10),round(np.imag(D_R_dl[i][j]),10)))
        
np.savetxt("constraints/D_R_dl.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_C_dl[i][j]),10),round(np.imag(D_C_dl[i][j]),10)))
        
np.savetxt("constraints/D_C_dl.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_C_dr[i][j]),10),round(np.imag(D_C_dr[i][j]),10)))
        
np.savetxt("constraints/D_C_dr.txt", file_input)   # write

file_input = []

for i in range(n_gi_edge_sts):
    for j in range(n_gi_edge_sts):
        file_input.append((i+1,j+1,round(np.real(D_L_dr[i][j]),10),round(np.imag(D_L_dr[i][j]),10)))
        
np.savetxt("constraints/D_L_dr.txt", file_input)   # write

file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_R_d[i][j]),10),round(np.imag(D_R_d[i][j]),10)))
        
np.savetxt("constraints/D_R_d.txt", file_input)   # write

file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_L_d[i][j]),10),round(np.imag(D_L_d[i][j]),10)))
        
np.savetxt("constraints/D_L_d.txt", file_input)   # write

file_input = []

for i in range(n_gi_st):
    for j in range(n_gi_st):
        file_input.append((i+1,j+1,round(np.real(D_C_d[i][j]),10),round(np.imag(D_C_d[i][j]),10)))
        
np.savetxt("constraints/D_C_d.txt", file_input)   # write